version: "3"

services:
  lovoo_dataset:
    image: levin/lp-service
    expose:
      - 7777
    ports:
      - "7777:7777"
  prometheus:
    image: prom/prometheus:v2.20.0
    container_name: prometheus
    expose:
      - 9090
    volumes:
      - prometheus_data:/prometheus
      - /c/py/liveproj/monitoring/prometheus:/etc/prometheus
    command:
      - '--storage.tsdb.retention.time=48h'
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:7.1.1
    container_name: grafana
    volumes:
      - grafana_data2:/var/lib/grafana
      - /c/py/liveproj/monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    restart: unless-stopped
    volumes:
      - /c/py/liveproj/monitoring/caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - "9090:9090"
      - "3000:3000"

volumes:
  prometheus_data: {}
  grafana_data2: {}
