version: "3"
services:
  prometheus:
    build: .
    image: prom/prometheus:v2.20.0
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - /c/py/liveproj/monitoring/prometheus:/etc/prometheus
    command:
      - '--storage.tsdb.retention.time'
      - '48h'
      - '--storage.tsdb.path'
      - '/prometheus'
      - '--config.file'
      - '/etc/prometheus/prometheus.yml'
    restart: unless-stopped
  grafana:
    image: grafana/grafana:7.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - /c/py/liveproj/monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
        GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
        GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
        

volumes:
  prometheus_data: {}
  grafana_data: {}
